---
- name: add global rdoc options
  become: yes
  tags:
    - ruby
    - config
  copy:
    src: gemrc
    dest: /etc/gemrc

- name: clone repo
  become: yes
  become_user: "{{ rbenv_user }}"
  git:
    repo=https://github.com/sstephenson/rbenv.git
    dest="/home/{{ rbenv_user }}/.rbenv"
    clone=yes
    update=yes
    version="v1.0.0"

- name: export PATH
  become: yes
  lineinfile:
    dest=/home/{{ rbenv_user }}/.profile
    line='export PATH="$HOME/.rbenv/bin:$PATH"'
    regexp="rbenv/bin"
    state=present
    create=yes
    owner="{{ rbenv_user }}"
    group="{{ rbenv_user }}"

- name: add rbenv init
  become: yes
  lineinfile:
    dest=/home/{{ rbenv_user }}/.profile
    line='eval "$(rbenv init -)"'
    regexp='rbenv init'
    state=present
    owner="{{ rbenv_user }}"
    group="{{ rbenv_user }}"

- name: mkdir ~/.rbenv/plugins
  file: path=/home/{{ rbenv_user }}/.rbenv/plugins state=directory
        owner={{ rbenv_user }} group={{ rbenv_user }} mode=0755

- name: install rbenv plugins
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=git://github.com/sstephenson/ruby-build.git 
       dest=/home/{{ rbenv_user }}/.rbenv/plugins/ruby-build

- name: install rbenv-gem-rehash
  git: repo=https://github.com/sstephenson/rbenv-gem-rehash.git
       dest=/home/{{ rbenv_user }}/.rbenv/plugins/rbenv-gem-rehash

- name: chown .rbenv dir
  command: chown -R {{ rbenv_user }}.{{ rbenv_user }} /home/{{ rbenv_user }}/.rbenv
