---
  - include: install.yml

  - name: install ruby {{ ruby_version }}
    become: yes
    become_user: "{{ rbenv_user }}"
    shell: ~/.rbenv/bin/rbenv install {{ ruby_version }}

  - name: set default version
    become: yes
    become_user: "{{ rbenv_user }}"
    shell: ~/.rbenv/bin/rbenv global {{ ruby_version }}

  - name: set rehash
    become: yes
    become_user: "{{ rbenv_user }}"
    shell: ~/.rbenv/bin/rbenv rehash

  - name: add default version
    become: yes
    become_user: "{{ rbenv_user }}"
    shell: "echo {{ ruby_version }} > ~/.rbenv/version"
